- name: Using the IBM Storage Virtualize collection For mTLS self signed certificate creation
  hosts: localhost
  collections:
    - ibm.storage_virtualize
  gather_facts: no
  connection: local
  vars_files:
    - PBR_variable.txt
  tasks:
    - name: Generate certificate on primary
      ibm_svctask_command:
        command: [ "svctask chsystemcert -mkselfsigned" ]
        clustername: "{{primary_cluster_ip}}"
        username: "{{primary_cluster_username}}"
        password: "{{primary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
    - name: Generate certificate on secondary
      ibm_svctask_command:
        command: [ "svctask chsystemcert -mkselfsigned" ]
        clustername: "{{secondary_cluster_ip}}"
        username: "{{secondary_cluster_username}}"
        password: "{{secondary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
    - name: Export SSL certificate internally on primary
      ibm_sv_manage_ssl_certificate:
        clustername: "{{primary_cluster_ip}}"
        username: "{{primary_cluster_username}}"
        password: "{{primary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
        certificate_type: "system"
    - name: Export SSL certificate internally on secondary
      ibm_sv_manage_ssl_certificate:
        clustername: "{{secondary_cluster_ip}}"
        username: "{{secondary_cluster_username}}"
        password: "{{secondary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
        certificate_type: "system"
    - name: Create truststore on primary
      ibm_sv_manage_truststore_for_replication: 
        clustername: "{{primary_cluster_ip}}"
        username: "{{primary_cluster_username}}"
        password: "{{primary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
        name: trust
        remote_clustername: "{{secondary_cluster_ip}}"
        remote_username: "{{secondary_cluster_username}}"
        remote_password:  "{{secondary_cluster_password}}"
        state: "present"
    - name: Create truststore on secondary
      ibm_sv_manage_truststore_for_replication: 
        clustername: "{{secondary_cluster_ip}}"
        username: "{{secondary_cluster_username}}"
        password: "{{secondary_cluster_password}}"
        log_path: "{{ log_path | default('/tmp/ansiblePB.debug') }}"
        name: trust
        remote_clustername: "{{primary_cluster_ip}}"
        remote_username: "{{primary_cluster_username}}"
        remote_password: "{{primary_cluster_password}}"
        state: "present"
